# Generated by Django 5.2.5 on 2025-08-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('apellidoCliente', models.CharField(max_length=100)),
                ('fotoCliente', models.CharField(max_length=200)),
                ('correoCliente', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=200)),
                ('telefonoCliente', models.CharField(max_length=20)),
                ('tipoDocCliente', models.CharField(choices=[('CC', 'Cedula'), ('PAS', 'Pasaporte'), ('CE', 'Cedula Extranjeria')], max_length=20)),
                ('numeroDocCliente', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEvento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaquete', models.CharField(max_length=50)),
                ('descripcionPaquete', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCita', models.DateField()),
                ('horaCita', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('comentario', models.TextField(max_length=200)),
                ('clienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.cliente')),
                ('eventoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.evento')),
            ],
        ),
    ]
