# Generated by Django 5.2.5 on 2025-08-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_cliente_fotocliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paquetes',
            new_name='Paquete',
        ),
    ]
