# Generated by Django 5.2.5 on 2025-08-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_paquetes_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fotoCliente',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/fotos_cliente/'),
        ),
    ]
