# Generated by Django 5.2.5 on 2025-09-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_cliente_fotocliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='clienteFK',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='eventoFK',
        ),
        migrations.DeleteModel(
            name='Paquete',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
