# Generated by Django 5.2.5 on 2025-09-01 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('todo', '0005_remove_cita_clientefk_remove_cita_eventofk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCita', models.DateField()),
                ('horaCita', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('comentario', models.TextField(max_length=200)),
                ('clienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.cliente')),
                ('eventoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
        ),
    ]
